# need to use sudo-enabled containers for additional RAM
sudo: required
language: java
jdk: oraclejdk12
python:
  - "3.6"
before_script:
  - export WYVERN_HOME="$(pwd)"
  - export _JAVA_OPTIONS="-Xmx6144m -Xms512m"
script:
  - echo "hello"
notifications:
  email:
    recipients:
      - cchu2@andrew.cmu.edu